# Generated by Django 5.2.7 on 2025-11-02 16:56

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
                ('lot', models.CharField(blank=True, max_length=10, null=True)),
                ('parcel', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('gid', models.CharField(max_length=64, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='core_parcel_geom_c7a240_gist')],
            },
        ),
    ]
