# Generated by Django 5.2.7 on 2025-11-04 19:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parcel_chacra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_tokens', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('AMBIGUA', 'AMBIGUA'), ('INCOMPLETA', 'INCOMPLETA'), ('NO_MATCH', 'NO_MATCH')], max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized', models.CharField(blank=True, default='', max_length=240)),
                ('llm_reason', models.TextField(blank=True, default='')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('quality', models.CharField(blank=True, max_length=1)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.building')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.street')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
