# Generated by Django 5.2.7 on 2025-11-04 22:00

from django.db import migrations


from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_querylog'),
    ]

    operations = [
        # 1) Renombrar columna result -> status si existe
        migrations.RunSQL(
            sql="ALTER TABLE core_querylog RENAME COLUMN IF EXISTS result TO status;",
            reverse_sql="ALTER TABLE core_querylog RENAME COLUMN IF EXISTS status TO result;",
        ),

        # 2) Agregar columnas faltantes (idempotente)
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_querylog
                ADD COLUMN IF NOT EXISTS normalized varchar(240) DEFAULT '' NOT NULL,
                ADD COLUMN IF NOT EXISTS llm_reason text DEFAULT '' NOT NULL,
                ADD COLUMN IF NOT EXISTS result_json jsonb DEFAULT '{}'::jsonb NOT NULL,
                ADD COLUMN IF NOT EXISTS score double precision DEFAULT 0 NOT NULL,
                ADD COLUMN IF NOT EXISTS quality varchar(1) DEFAULT '' NOT NULL
            """,
            reverse_sql="""
                ALTER TABLE core_querylog
                DROP COLUMN IF EXISTS normalized,
                DROP COLUMN IF EXISTS llm_reason,
                DROP COLUMN IF EXISTS result_json,
                DROP COLUMN IF EXISTS score,
                DROP COLUMN IF EXISTS quality
            """,
        ),
    ]
